//
// mcs96ops_decls.hxx
//
// mt32-pi - A baremetal MIDI synthesizer for Raspberry Pi
// Copyright (C) 2020-2023 Dale Whinham <daleyo@gmail.com>
//
// D-110 emulation core added 2026, ported from the D-110 VST Emulator project
// (https://github.com/luginf/d110-vst-emulator) by Alan <luginfo10@gmail.com>.
//
// This file is part of mt32-pi.
//
// mt32-pi is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// mt32-pi is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// mt32-pi. If not, see <http://www.gnu.org/licenses/>.
//

// Method declarations for the ~230 opcode bodies implemented in src/synth/d110/mcs96ops.hxx -
// machine-generated (see mcs96_cpu.h), included into Mcs96Cpu's private section.
	void skip_immed_1b_full();
	void clr_direct_1w_full();
	void not_direct_1w_full();
	void neg_direct_1w_full();
	void xch_direct_2w_full();
	void dec_direct_1w_full();
	void ext_direct_1w_full();
	void inc_direct_1w_full();
	void shr_immed_or_reg_2w_full();
	void shl_immed_or_reg_2w_full();
	void shra_immed_or_reg_2w_full();
	void shrl_immed_or_reg_2w_full();
	void shll_immed_or_reg_2w_full();
	void shral_immed_or_reg_2w_full();
	void norml_direct_2e_full();
	void clrb_direct_1b_full();
	void notb_direct_1b_full();
	void negb_direct_1b_full();
	void xchb_direct_2b_full();
	void decb_direct_1b_full();
	void extb_direct_1b_full();
	void incb_direct_1b_full();
	void shrb_immed_or_reg_2b_full();
	void shlb_immed_or_reg_2b_full();
	void shrab_immed_or_reg_2b_full();
	void sjmp_rel11_full();
	void scall_rel11_full();
	void jbc_brrel8_full();
	void jbs_brrel8_full();
	void and_direct_3w_full();
	void and_immed_3w_full();
	void and_indirect_3w_full();
	void and_indexed_3w_full();
	void add_direct_3w_full();
	void add_immed_3w_full();
	void add_indirect_3w_full();
	void add_indexed_3w_full();
	void sub_direct_3w_full();
	void sub_immed_3w_full();
	void sub_indirect_3w_full();
	void sub_indexed_3w_full();
	void mulu_direct_3w_full();
	void mulu_immed_3w_full();
	void mulu_indirect_3w_full();
	void mulu_indexed_3w_full();
	void mul_direct_3w_full();
	void mul_immed_3w_full();
	void mul_indirect_3w_full();
	void mul_indexed_3w_full();
	void andb_direct_3b_full();
	void andb_immed_3b_full();
	void andb_indirect_3b_full();
	void andb_indexed_3b_full();
	void addb_direct_3b_full();
	void addb_immed_3b_full();
	void addb_indirect_3b_full();
	void addb_indexed_3b_full();
	void subb_direct_3b_full();
	void subb_immed_3b_full();
	void subb_indirect_3b_full();
	void subb_indexed_3b_full();
	void mulub_direct_3e_full();
	void mulub_immed_3e_full();
	void mulub_indirect_3e_full();
	void mulub_indexed_3e_full();
	void mulb_direct_3e_full();
	void mulb_immed_3e_full();
	void mulb_indirect_3e_full();
	void mulb_indexed_3e_full();
	void and_direct_2w_full();
	void and_immed_2w_full();
	void and_indirect_2w_full();
	void and_indexed_2w_full();
	void add_direct_2w_full();
	void add_immed_2w_full();
	void add_indirect_2w_full();
	void add_indexed_2w_full();
	void sub_direct_2w_full();
	void sub_immed_2w_full();
	void sub_indirect_2w_full();
	void sub_indexed_2w_full();
	void mulu_direct_2w_full();
	void mulu_immed_2w_full();
	void mulu_indirect_2w_full();
	void mulu_indexed_2w_full();
	void mul_direct_2w_full();
	void mul_immed_2w_full();
	void mul_indirect_2w_full();
	void mul_indexed_2w_full();
	void andb_direct_2b_full();
	void andb_immed_2b_full();
	void andb_indirect_2b_full();
	void andb_indexed_2b_full();
	void addb_direct_2b_full();
	void addb_immed_2b_full();
	void addb_indirect_2b_full();
	void addb_indexed_2b_full();
	void subb_direct_2b_full();
	void subb_immed_2b_full();
	void subb_indirect_2b_full();
	void subb_indexed_2b_full();
	void mulub_direct_2b_full();
	void mulub_immed_2b_full();
	void mulub_indirect_2b_full();
	void mulub_indexed_2b_full();
	void mulb_direct_2b_full();
	void mulb_immed_2b_full();
	void mulb_indirect_2b_full();
	void mulb_indexed_2b_full();
	void or_direct_2w_full();
	void or_immed_2w_full();
	void or_indirect_2w_full();
	void or_indexed_2w_full();
	void xor_direct_2w_full();
	void xor_immed_2w_full();
	void xor_indirect_2w_full();
	void xor_indexed_2w_full();
	void cmp_direct_2w_full();
	void cmp_immed_2w_full();
	void cmp_indirect_2w_full();
	void cmp_indexed_2w_full();
	void divu_direct_2w_full();
	void divu_immed_2w_full();
	void divu_indirect_2w_full();
	void divu_indexed_2w_full();
	void div_direct_2w_full();
	void div_immed_2w_full();
	void div_indirect_2w_full();
	void div_indexed_2w_full();
	void orb_direct_2b_full();
	void orb_immed_2b_full();
	void orb_indirect_2b_full();
	void orb_indexed_2b_full();
	void xorb_direct_2b_full();
	void xorb_immed_2b_full();
	void xorb_indirect_2b_full();
	void xorb_indexed_2b_full();
	void cmpb_direct_2b_full();
	void cmpb_immed_2b_full();
	void cmpb_indirect_2b_full();
	void cmpb_indexed_2b_full();
	void divub_direct_2e_full();
	void divub_immed_2e_full();
	void divub_indirect_2w_full();
	void divub_indexed_2w_full();
	void divb_direct_2e_full();
	void divb_immed_2e_full();
	void divb_indirect_2w_full();
	void divb_indexed_2w_full();
	void ld_direct_2w_full();
	void ld_immed_2w_full();
	void ld_indirect_2w_full();
	void ld_indexed_2w_full();
	void addc_direct_2w_full();
	void addc_immed_2w_full();
	void addc_indirect_2w_full();
	void addc_indexed_2w_full();
	void subc_direct_2w_full();
	void subc_immed_2w_full();
	void subc_indirect_2w_full();
	void subc_indexed_2w_full();
	void ldbze_direct_2e_full();
	void ldbze_immed_2e_full();
	void ldbze_indirect_2w_full();
	void ldbze_indexed_2w_full();
	void ldb_direct_2b_full();
	void ldb_immed_2b_full();
	void ldb_indirect_2b_full();
	void ldb_indexed_2b_full();
	void addcb_direct_2b_full();
	void addcb_immed_2b_full();
	void addcb_indirect_2b_full();
	void addcb_indexed_2b_full();
	void subcb_direct_2b_full();
	void subcb_immed_2b_full();
	void subcb_indirect_2b_full();
	void subcb_indexed_2b_full();
	void ldbse_direct_2e_full();
	void ldbse_immed_2e_full();
	void ldbse_indirect_2w_full();
	void ldbse_indexed_2w_full();
	void st_direct_2w_full();
	void st_indirect_2w_full();
	void st_indexed_2w_full();
	void stb_direct_2b_full();
	void stb_indirect_2b_full();
	void stb_indexed_2b_full();
	void push_direct_1w_full();
	void push_immed_1w_full();
	void push_indirect_1w_full();
	void push_indexed_1w_full();
	void pop_direct_1w_full();
	void pop_indirect_1w_full();
	void pop_indexed_1w_full();
	void jnst_rel8_full();
	void jnh_rel8_full();
	void jgt_rel8_full();
	void jnc_rel8_full();
	void jnvt_rel8_full();
	void jnv_rel8_full();
	void jge_rel8_full();
	void jne_rel8_full();
	void jst_rel8_full();
	void jh_rel8_full();
	void jle_rel8_full();
	void jc_rel8_full();
	void jvt_rel8_full();
	void jv_rel8_full();
	void jlt_rel8_full();
	void je_rel8_full();
	void djnz_rrel8_full();
	void br_indirect_1n_full();
	void ljmp_rel16_full();
	void lcall_rel16_full();
	void ret_none_full();
	void pushf_none_full();
	void popf_none_full();
	void trap_none_full();
	void clrc_none_full();
	void setc_none_full();
	void di_none_full();
	void ei_none_full();
	void clrvt_none_full();
	void nop_none_full();
	void rst_none_full();
	void fetch_full();
	void fetch_noirq_full();
